### ISSUE TITLE
the download link said page not find 

### ISSUE THREAD

**Issue by ghost** [the-synister/the-source#2] opened 2016-03-18 23:24 UTC
i go to https://the-synister.github.io/#download
and click the download....but page not find

**Comment by juanecabellob** [comment] 2016-03-19 16:26
Which OS do you have? I cannot reproduce it

**Comment by RyanHerbert** [comment] 2016-03-19 16:57
It looks like the link is broken on Windows.  

The download link is pointing to: 
https://github.com/the-synister/the-source/releases/download/release1-0-2/synister-Win-1.0.2.exe

**Comment by juanecabellob** [comment] 2016-03-19 17:02
it is now fixed. can you try again?

**Comment by RyanHerbert** [comment] 2016-03-19 17:06
Looks to be good.

**Comment by juanecabellob** [comment] 2016-03-19 17:07
perfect! Thanks! I'm closing it then

**Closed as completed by juanecabellob** 2016-03-19 17:07 UTC

**Comment by ghost** [comment] 2016-03-19 23:58
Oh, it is ok now, thanks

juanecabellob 於 20/3/2016 1:02 寫道:
